// <auto-generated />
namespace WcfServiceHosting.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class fixeduserinfoaddedrequiredattribute : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fixeduserinfoaddedrequiredattribute));
        
        string IMigrationMetadata.Id
        {
            get { return "201701122129053_fixed user info - added required attribute"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
